### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by dochypermoose** [flothesof/ankiextendedheatmap2023#1]
Not sure if there's a conflict with one of my other addons, but I get this error when trying to startup

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-08 06:11:06
Add-ons possibly involved: ⁨Rating Heatmap For Anki 21 Updated November 2023⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 506, in loadProfile
  File "aqt.main", line 1061, in maybe_auto_sync_on_open_close
  File "aqt.main", line 1056, in _sync_collection_and_media
  File "aqt.sync", line 123, in sync_collection
  File "aqt.taskman", line 104, in with_progress
  File "aqt.taskman", line 68, in run_in_background
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 152, in success
  File "aqt.deckbrowser", line 168, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/243020312/__init__.py", line 252, in displayHeatMap
    content.stats += deckbrowserRenderStats()
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/243020312/__init__.py", line 201, in deckbrowserRenderStats
    a = Activity(mw.col)
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/243020312/activity.py", line 19, in __init__
    self.offset = self._getColOffset()
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/243020312/activity.py", line 103, in _getColOffset
    start_date = datetime.fromtimestamp(selfmore.col.crt)
NameError: name 'selfmore' is not defined

**Comment by flothesof** [comment]
Hi, thanks for reporting the problem. Let me investigate and I’ll try to come back to you.

**Comment by flothesof** [comment]
There was a bug on my side. This is fixed by the latest commit. I’ve uploaded the new version to Ankiweb. Could you kindly let me know if it works for you?
